---
title: "Integrating geographic analysis in transport planning workflows with open source software"
author: "Robin Lovelace"
date: '`r Sys.Date()`'
output:
  github_document: default
  pdf_document: default
  word_document: default
bibliography: references.bib
---

```{r, echo=FALSE, eval=FALSE}
# get citations
refs_sof = RefManageR::ReadZotero(group = "418217", .params = list(collection = "JFR868KJ", limit = 100))
refs_gis = RefManageR::ReadZotero(group = "418217", .params = list(collection = "KUXG5CJL", limit = 100))
refs_geo = RefManageR::ReadZotero(group = "418217", .params = list(collection = "9K6FRP6N", limit = 100))
refs = c(refs_sof, refs_gis, refs_geo)
refs_df = as.data.frame(refs)
# View(refs_df)
RefManageR::WriteBib(refs, "references.bib")

n_words = wordcountaddin::word_count("README.Rmd")
word_count = readr::read_csv("word-count.csv")
word_count_new = rbind(word_count, data.frame(date = Sys.Date(), n_words))
readr::write_csv(word_count_new, "word-count.csv")
```


# Abstract {-}

Software for working with geographic data has long been used in transport planning.
Transport is an inherently geographic activity, involving movement through space, from one location to another on the face of the Earth, along more or less complicated trajectories defined by ways (highways, cycleways, footways etc) that can be defined as a spatial network.
One would therefore expect that geographic data structures and analysis would be a *vital and inbuilt* part of transport planning software.
This has not historically been the case, however.
A dichotomy between 'geographic/non-geographic' components of transport planning analysis persists: workflows in academic, public sector and private consultancy transport planning contexts still tend to separate vital geographic processing and map making stages from the rest of the analysis.
This paper argues that this division inadvertently damages transport planning in three main ways, by:
(1) reducing researcher effectiveness and slows down work due to the time-consuming process of 'context switching';
(2) inhibiting reproducibility, by requiring transport planners to learn, install and manage different programs for geographic and non-geographic aspects of their job; and, more fundamentally, 
(3) preventing transport planners, decision makers and others who use the outputs of transport planning from seeing vital geographic relationships, concepts and consequences, by implicitly encouraging geographic work to be considered as an 'add-on'.
Building on this critique, this paper outlines solutions using popular and free open source software ecosystems (R, Python and QGIS) that enable geographic components of data analysis, modelling and visualisation to be *embedded within* transport planning workflows.
This process of integrating geographical analyis has implications that go beyond academic transport research: more explicit inclusion of geography in transport planning will lead to better decision making, something that is vital in the context of the global transition away from the private motor car that the climate, obesity and air pollution crises demand. 

# Introduction

Transport planning is an applied discipline involving not only the design of ways --- including highways, railways, cycleways and footways --- but also envisioning the future and making the case for change [@oflaherty_transport_1997].
Successful transport plans are long-term strategies guided by citywide, regional and even national visions that will have material benefits for people and the local and global environment for generations to come.
But transport plans are also inherently spatial: the ways and other pieces of transport infrastructure must *go somewhere* to optimise their ability to take people *where they want to go* [@rodrigue_geography_2013].

Transport planning is thus embedded within broad democratic processes *and* local geographic contexts.
Effective transport planning is inherently democratic because it determines about how public space is to be used, with impacts for generations to come.
If transport plans are developed by unacountable technocrats with little understanding of transport's impacts on other economies, the results can be severe: the transport system now is the "leading cause of death for children and young adults aged 5-29 years" through road traffic casualties alone, with 1.35 million people killed and tens of millions injured and disabled each year [@world_health_organization_global_2018].
The air pollution impacts could be even worse, with a growing body of research linking air pollution to Alzheimer's disease, lung cancer and heart disease among hundreds of millions of sufferers worldwide [@kampa_human_2008; @kilian_emerging_2018].
Transport is responsible for a quarter of global greenhouse gas emissions and growing [@harrison_environmental_2017], and is one of the hardest sectors to decarbonise [@moriarty_prospects_2008], meaning that evidence-based plans to reduce transport energy use is an urgent priority affecting the global population and especially the projected 1.4 billion people who will live in low elevation (less than 10 m above sea level) coastal zones by 2060 [@neumann_future_2015].

Despite their global impacts, transport systems and the networks of physical infrastructure that underpin them are also highly localised [@barthelemy_spatial_2011; @levinson_network_2012] and to some degree dynamic [@xie_evolving_2011] phenomena.
Effective transport planning therefore requires a deep understanding of the geography.
Where is existing infrastructure and 'demand' (current and potential travel) located?
How will transport patterns shift in the future?
And where will different types of intervention be most effective?
Tools that can help answer these questions are becoming an increasingly important part of the transport planner's cabinet [@te_brommelstroet_developing_2008].

To illustrate this point, imagine fundamental changes that could be made to tax system in support a transition away from fossil fuels.
Interventions such as carbon taxes would undoubtedly have geographic implications, but the intervention itself (charging a fixed price for the extraction and sale of atmosphere polluting substances) could be essentially non-geographic.
Notwithstanding changes to national policies relating to transport, transport planning interventions, by contrast, are inherently spatial.
However, even high level national plans for a walking and cycling revolution must be implemented locally, down to the level of streets, as illustrated by the still ongoing local implementation of Dutch cycling ambitions [@pucher_making_2008]. 
The political-democratic and local-geographic aspects of transport planning can be considered in isolation, but an integrated approach is necessary for effective policies [@hull_policy_2008].
This is well illustrated by prominent Mayoral transport policies in cities such as 
London[^1],
Paris^[
The current Mayor of Paris, Anne Hidalgo, sees transport as a priority and has plans to make public transport free. See 
[paris.fr](https://www.paris.fr/rechercher/transport).
],
and Bogotá^[
Bogotá has an innovative and prominent transport policy, led by the two times mayor Enrique Peñalosa, who has led the roll-out of major bus and cycleway projects in the city. See [sitp.gov.co](https://www.sitp.gov.co/).
].


[^1]: Transport is a major electoral issue in London and the current Mayor, Sadiq Kahn, has made tackling air pollution a policy priority. See [tfl.gov.uk/corporate/about-tfl/the-mayors-transport-strategy](https://tfl.gov.uk/corporate/about-tfl/the-mayors-transport-strategy).


With issues such as climate change, air pollution, obesity and social inequalities high on the political agenda, it is likely that many other cities will adopt innovative transport strategies.
This raises questions of great relevance to researchers:
how will future transport be designed?
and based on what evidence and analysis will interventions be implemented?
Both questions link to transport planning methodologies which, as this paper outlines, increasingly require geographic analysis.
Furthermore, the policy context increasingly demands transparency and citizen involvement in the decision-making process, which only software that is open source and reliably deliver, making an exploration of open source options for transport planning workflows timely.

Practical transport planning is evolving in response to the policy drivers: transport policies that are evidence-based and grounded in realistic models of change under different scenarios of the future are far more likely to be successful than policies based on ideological commitment and good intentions alone.
With unprecedented access to increasingly detailed datasets on transport behaviours and infrastructure, transport planners today can ensure that their designs are more evidence-based that ever.
Furthermore, advances in software and hardware allow not only for current transport systems to be modelled at high temporal and geographic resolution, but for future scenarios and 'model experiments' to be developed, which can lead to identification and implementation of the most effective interventions.
With the explosion in open source software, which has come to dominate data science, there is now also a unique opportunity for transport planning to become a more transparent and democratically accountable enterprise.

However, this dream of data driven, participatory and open transport planning has yet to emerge.
Transport planning as a discipline has been slow to adapt to the 'data revolution' and, while it evolves to enable a wider range of input data sources and analysis 'in the cloud', the open source element of the dream is conspicuously lacking.

Something on incumbent software...

Data preprocessing and analysis stages are generally done in dedicated transport planning and spreadsheet software.
Geographic analysis and cartographic visualisation stages are generally done in a dedicated 'geographic information system' (GIS).

<!-- This stuff could go in the introduction. -->
The paper traces how this undesirable situation has arisen due to historical specialisation and monopolisation of transport planning software, based on existing literature, before outlining an integrated approach that combines data analysis and geographic processing stages in a single workflow.
Three software ecosystems (R, Python and QGIS) are reviewed in detail; alternative current and potential future approaches, including 'cloud lock in' are discussed; and the relative merits of different approaches are discussed.
Building on this discussion, I argue that integrating data analysis and geographic processing in a single analysis has major advantages and outlines concrete steps that researchers, public sector transport planners, and transport planning analysts and consultants can use.
The paper concludes that 'integrated approach' can support efficient, scalable and reproducible transport planning workflows which can provide a strong and transparent evidence base needed for rapid transition away from fossil fuels in the transport sector.

# The geographic and non-geographic division of labour in Transport Planning

# Integrating geographic analysis in transport planning with open source software

## R

[@r_core_team_r:_2019]

[@bivand_implementing_2006]

[@pebesma_software_2015]


[@bivand_applied_2013]


## Python

[@rossum_python_1995]


## QGIS

[@qgis_development_team_qgis_2019]

# Conclusion

# References
